### ISSUE TITLE
_login failed with msg:"baidupcsapi.api.LoginFailed: unknown err_id=18"

### ISSUE THREAD

**Issue by skyLiao** [ly0/baidupcsapi#11]
login failed now. do you have a java version api? thx.

here is the log:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "baidupcsapi/api.py", line 398, in __init__
    super(PCS, self).__init__(username, password, api_template, captcha_func=captcha_callback)
  File "baidupcsapi/api.py", line 135, in __init__
    self._initiate()
  File "baidupcsapi/api.py", line 181, in _initiate
    self._login()
  File "baidupcsapi/api.py", line 282, in _login
    self._check_account_exception(result.content)
  File "baidupcsapi/api.py", line 320, in _check_account_exception
    raise LoginFailed(msg)
baidupcsapi.api.LoginFailed: unknown err_id=18

**Comment by capric8416** [comment]
登录失败，错误码18，目前原因未知。
请问重试可以解决问题吗？你的帐号在网页上登录百度网盘是否正常？

**Comment by ly0** [comment]
@capric8416 不知道你是否介意我把你加到这个项目的collaborators？

**Comment by capric8416** [comment]
@ly0 谢谢啦，转存功能有个bug还没修复（errno=2），有时间的话帮忙调一下哦
https://github.com/capric8416/baidupcsapi

**Comment by skyLiao** [comment]
网页端是可以登录的。重试也不能解决。是百度api更新了？你们还可以登录使用吗？

**Comment by capric8416** [comment]
@skyLiao 我这边是可以登录的，你试试把cookie删除了
cookie文件在代码目录下面，以“.用户名”开始

**Comment by ly0** [comment]
我这里也是可以登录的
```python
In [2]: from baidupcsapi.api import PCS

In [3]: a = PCS('xxx', 'xxxx')
https://passport.baidu.com/cgi-bin/genimage?xxxxx(省略)
open url aboved with your web browser, then input verify code > 3179

In [4]: 
```

**Comment by skyLiao** [comment]
我是新clone下来的代码。

**Comment by xboys** [comment]
这个是百度最新手机验证导致的，手机验证通过后，就没有这个问题了
