### ISSUE TITLE
有没有pcs.share的使用实例啊？

### ISSUE THREAD

**Issue by xboys** [ly0/baidupcsapi#12]
分享文件或文件夹
~~~~~~~~~~~~~~~~~
.. automethod:: baidupcsapi.PCS.share

现在百度网盘，有"公开分享“和”私密分享“，请问这个对应的PCS.share有没有具体的例子？

非常感谢！

**Comment by ly0** [comment]
参考下这个？

http://baidupcsapi.readthedocs.org/en/latest/api.html?highlight=share#baidupcsapi.PCS.share

**Comment by xboys** [comment]
我看过这个API介绍，
file_ids – 要分享的文件fid列表
这个参数怎么获取？ 自己试了半天，如fs_id，不对啊。望指点下。

多谢！

**Comment by ly0** [comment]
list dir里应该是有的


Sent from phone.





On Sun, Sep 20, 2015 at 11:22 PM -0700, "xboys" <notifications@github.com> wrote:












我看过这个API介绍，

file_ids – 要分享的文件fid列表

这个参数怎么获取？ 自己试了半天，如fs_id，不对啊。望指点下。



多谢！
