### ISSUE TITLE
能写一个python3的版本吗

### ISSUE THREAD

**Issue by 0312birdzhang** [ly0/baidupcsapi#15]
做一下伸手党，用2to3转换的有很多问题 ;)

**Comment by ly0** [comment]
你太懒了喵！

**Comment by 0312birdzhang** [comment]
@ly0 对python3不太熟悉，一直用python2，那些字符编码神马的搞得好烦躁. =。=

**Comment by lilydjwg** [comment]
@0312birdzhang 所以当初我遇到几个 UnicodeError 之后，我果然抛弃 2 改学 3，除了等各种库的支持之外其它都挺顺利的=w=

**Comment by 0312birdzhang** [comment]
@lilydjwg 现在好多“老人家”写的好东西都是2的 :sweat_smile:

**Comment by ly0** [comment]
@lilydjwg 233，看到3.5有`async`以后吸引力太大了

**Comment by 0312birdzhang** [comment]
@ly0 所以，来一发python3的如何 :kissing_heart:
