### ISSUE TITLE
弱弱的问一句，下载的文件跑哪里去了？

### ISSUE THREAD

**Issue by 0312birdzhang** [ly0/baidupcsapi#17]
刚才在做python3版本的测试，发现下载了东西虽然response码是200，但是找不到下载的文件。
然后我切换到python2版本，下载完也没有找到
我用find找了整个磁盘也没找到 :joy: 
用的pcs.download(",header)

**Comment by ly0** [comment]
只是返回数据不保存文件哦建议用这个 `download_url`

**Comment by 0312birdzhang** [comment]
嗯，用<code>download_url</code>可以，3Q
