### ISSUE TITLE
请问获取的下载地址是有限速吗？

### ISSUE THREAD

**Issue by a1exwang** [ly0/baidupcsapi#21]

**Comment by ly0** [comment]
好像现在百度网盘非会员的似乎有限速，不知道网盘客户端也是这样么?

**Comment by a1exwang** [comment]
改了useragent就没有限速了，不过我有会员~

On Dec 22, 2015 11:47 AM, "latyas(懒)" <notifications@github.com> wrote:

好像现在百度网盘非会员的似乎有限速，不知道网盘客户端也是这样么?
