### ISSUE TITLE
作者菊苣好！感谢及询问！

### ISSUE THREAD

**Issue by hejiheji001** [ly0/baidupcsapi#23]
大概半个月前我用JAVA写了一个云音乐[下载器](https://github.com/hejiheji001/CloudMusic)，百度云[离线器](https://github.com/hejiheji001/BDNM)并且把它们合并成了云音乐转存到百度离线任务的[转存器](https://github.com/hejiheji001/CloudMusicToYunPan)（请务必忽略我这没有创意的起名方式
JAVA写的 三个程序都Works Well

然而今天在本地试了下 发现登录失败 err_no = 257, 输入验证码后 err_no = 2
看了你的代码后认为可能是因为密码没有用RSA加密 但是有2个问题在此想请教一下

1 我用位于米国的VPS跑离线器没有问题 成功给自己的百度云加了任务 
但是用位于腐国的本机就有上述问题 不太清楚原因

2 不是很懂Python, 想请教下RSA的具体JAVA实现 以下是JAVA的代码 似乎不太行
````
        try {
            KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
            kpg.initialize(2048);
            KeyPair kp = kpg.genKeyPair();
            Key publicKey = kp.getPublic();
            Key privateKey = kp.getPrivate();

            KeyFactory fact = KeyFactory.getInstance("RSA");
            RSAPublicKeySpec pub = fact.getKeySpec(kp.getPublic(), RSAPublicKeySpec.class);
            RSAPrivateKeySpec priv = fact.getKeySpec(kp.getPrivate(), RSAPrivateKeySpec.class);
        }catch (Exception e){
            e.printStackTrace();
        }
````

最后～目测菊苣是ACG爱好者～ 有玩Google+么～ 我的是 [+FireAwayH](https://plus.google.com/+FireAwayH/posts) (于是拿出了绿箭

**Comment by ly0** [comment]
好像不太对，我不太懂java，你这段java的代码应该是产生一个公私钥对的，然而我们只需要公钥。

然后问题1就是。。有可能是百度让你验证邮箱或者手机号啥的 （毕竟一个帐号好多国家什么的）

G+已经follow你了  233333

**Comment by hejiheji001** [comment]
我今天测试了 发现之前vps成功是因为我缓存的cookie还没有过期 不需要登录
去掉cookie的话 同样登录失败
用网页进行登陆没有问题0.。0
但是我找不到关于err_no ＝ 2 的错误信息= =!

PS: 我感觉和RSA应该关系不大 因为你很早就开始用RSA了 而我是10+天前写的

**Comment by a1exwang** [comment]
@hejiheji001 你好, 我之前用ruby写过类似的下载器, 虽然没遇到这个问题, 但是好像遇到过errno 20, 然后根据这个
http://www-numi.fnal.gov/offline_software/srt_public_context/WebDocs/Errors/unix_system_errors.html,
发现果然是目录的问题
我猜errno在256以内的大概和c语言的errno含义是对应的, 希望能帮到你. ^_^
楼主可以多发一些代码, 光这些貌似看不出来什么不对?

**Comment by ly0** [comment]
@a1exwang 233 好像人家说的是百度网盘返回的错误代码的样子

**Comment by hejiheji001** [comment]
@a1exwang 感谢回复 我已经找到原因惹 >_<
