### ISSUE TITLE
请求支持python3，谢谢！

### ISSUE THREAD

**Issue by zhangithub** [ly0/baidupcsapi#29]
用pip安装后发现代码都是python2的，python3根本没法用，我尝试用2to3.py转换后发现bencode.py仍有些关于types代码没法用，于是我手动修改成了python3代码，可是运行后还是出现各种错误，这些错误超出我的能力范围。所以恳请您支持python3.x版本，不胜感激！

**Comment by ly0** [comment]
可以去掉bencode的依赖

**Comment by ly0** [comment]
多年后的今天 py3了
