### ISSUE TITLE
baidupanapi

### ISSUE THREAD

**Issue by zh-wowtv** [ly0/baidupcsapi#39]
请教一下，你在readme中提到baidupanapi，请问是什么？文档在哪里？谢谢

我想做一个获取百度云直链的应用（像这样：http://www.huangguofeng.com/gongju.php ），不知从何下手，有建议吗？多谢

**Comment by ly0** [comment]
只是曾经想改一下名字后来没改

可以参考
https://github.com/ly0/web.baidupan
https://github.com/ly0/baidu-fuse

仅供娱乐使用

**Comment by zh-wowtv** [comment]
谢谢，不过为何不能用于生产环境？

**Comment by ly0** [comment]
未经严格测试，不保证有各种问题呗～
