### ISSUE TITLE
Super_file里面有个Bug

### ISSUE THREAD

**Issue by dindom999** [ly0/baidupcsapi#4]
pip里似乎有个Bug，折腾了一天，都没找到原因。
主要是在用分片后用Super_file合并的时候总是出现：
'{"error_code":31023,"error_msg":"request body param error, it must be:param={&quot;block_list&quot;:[&quot;file_0_md5&quot;,&quot;file_1_md5&quot;,....]}","request_id":739767243}'
而事实上Block_list是对的。
我试着将两个步骤分成两个文件：先运行test1.py(用PCS.upload_tmpfile上传10个文件)，然后test2.py（用pcs.upload_superfile合并），结果居然成功了，
而将两个步骤合并成一个test.py却出现上面的错误信息。
然后我更新里这里的最新版本，问题就解决了。希望后来者不会象我这样浪费一天时间。

**Comment by ly0** [comment]
对不起对不起，pypi上的代码一直忘了同步，刚刚同步了一下代码。
感谢您 :)
