### ISSUE TITLE
验证码的问题

### ISSUE THREAD

**Issue by MathiasLuo** [ly0/baidupcsapi#40]
我每次请求都会更新 重新输入 验证码 特别不方便  能不能一直使用一份cookies或者自动识别验证码呀？

谢谢了

**Comment by ly0** [comment]
保存cookies是有的，就是不知道可能是不是不好使了。
识别验证码难度太高 。。。。

**Comment by MathiasLuo** [comment]
谢谢了  我想把这套api写在服务器 进行解析  不知道 你有没有什么比较好的构架？

**Comment by ly0** [comment]
？没看明白呢

**Comment by MathiasLuo** [comment]
就是说现在  我操作几下就回叫我重新输入验证码  有什么好的解决方案吗？

**Comment by MathiasLuo** [comment]
业务流程也就是  在服务器解析传送来的种子或者磁力链接 ，然后再返回客户端需要m3u8文件，现在出现的问题就是常常客户端请求两下，服务器就要我重新输入验证码，这样，不能投入生产呀。
谢谢你的答复

**Comment by ly0** [comment]
你是说离线下载吗？

**Comment by MathiasLuo** [comment]
对的，就是可能会频繁的要求我输入验证码，我想问的是除了使用识别验证码，还有没有其他的方案来解决这个。

**Comment by ly0** [comment]
这个是百度网盘的限制，唯一能想办法解决的只能是在前端让用户输入了。

**Comment by heipacker** [comment]
百度网盘主动做了这个限制吗？

**Comment by ly0** [comment]
@heipacker 嗯，可以试试在百度网盘界面上多搞几个离线下载，然后就会让你一直不停的输验证码
