### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by hannsen** [ly0/baidupcsapi#41]
When i try to log in i get stuck on a captcha loop. I'm always asked to input a captcha when the code is always correct.

It does not matter if my username/password is my right one or just garbage. always captcha

**Comment by ly0** [comment]
可能账号异常？

**Comment by hannsen** [comment]
google translate:
You may account abnormal?

I have a normal pan.baidu account

**Comment by ly0** [comment]
okay, reported by some people, captcha loop happened before sporadically, but I still have not encountered with that, so the only I can do is guessing maybe account is at abnormal status.
Have you tried another account?

**Comment by hannsen** [comment]
I ditched pan.baidu anyhow, because the upload was so slow and did not work

but I activated it with a german phone number from this link

https://passport.baidu.com/v2/?reg&u=http://pan.baidu.com&regType=1&tpl=netdisk&overseas=1
