### ISSUE TITLE
样例问题

### ISSUE THREAD

**Issue by edisonh** [ly0/baidupcsapi#5]
运行样例
from baidupcsapi import PCS
pcs = PCS('myaccount', 'mypassword')
print pcs.quota().content

结果打出console里面打出一串这样的东西，样例跑不起来
[48;5;231;38;5;231m▄[48;5;231;38;5;231m▄[48;5;231;38;5;23
5;231m▄[48;5;231;38;5;231m▄[48;5;231;38;5;231m▄[48;5;231
;231;38;5;231m▄[48;5;231;38;5;231m▄[48;5;231;38;5;231m▄[
captcha >

找了web.baidupan，运行也是这么个结果。

这个到底是怎么回事呢

**Comment by ly0** [comment]
看输出应该是要输入验证码，默认的输出验证码的方法仅限linux终端  
参考 https://github.com/ly0/baidupcsapi/issues/3 解决方案

**Comment by edisonh** [comment]
thx so much！
