### ISSUE TITLE
登录失败,请在弹出的窗口操作,或重新登录

### ISSUE THREAD

**Issue by zzploveyou** [ly0/baidupcsapi#57]
python2.7, pip安装的. 
`pcs = PCS(username, passwd)`
输入验证码后出现此错误!

**Comment by ly0** [comment]
pip上的有一段时间没更新了, 用github的代码
现在已经迁移到 python 3 了

*登录失败,请在弹出的窗口操作,或重新登录* 这个错误大概是需要在目标网络环境下进行一次手机认证或者邮箱认证的操作

**Comment by zzploveyou** [comment]
多谢.麻烦再问下,
输入验证码后又需要输入**Verification Code>.**是什么意思?

**Comment by ly0** [comment]
?你用的哪个版本的?

**Comment by ly0** [comment]
麻烦再更新一下 这个Verification code 应该是发到你邮箱里的一个验证码

**Comment by howzanh** [comment]
@zzploveyou  嗨，出现以下错误大概是什么问题，你有碰到过吗，win10 64位
![_20170913105444](https://user-images.githubusercontent.com/29419684/30357605-21006a58-9872-11e7-996c-18ed46256d20.png)

**Comment by ly0** [comment]
建议直接指定 captcha_handler ，这个库提交上来的实现可能不大好 @howzanh

**Comment by zzploveyou** [comment]
@ly0 更新后,邮箱收到验证码.输进入又会弹出
`  File "/usr/local/lib/python3.5/dist-packages/baidupcsapi-0.9.2-py3.5.egg/baidupcsapi/api.py", line 410, in _check_account_exception
    raise LoginFailed(msg)
baidupcsapi.api.LoginFailed: 登录失败,请在弹出的窗口操作,或重新登录`

**Comment by ly0** [comment]
@zzploveyou 你好，我的账号目前暂时无法触发验证码，我找找有没有别的账号测试。

**Comment by howzanh** [comment]
@ly0 你好，你们当前测试比较稳定的操作系统 版本能否告知我下，谢谢，比如 Mac，Linux  版本。

**Comment by ly0** [comment]
@howzanh 建议在非windows下使用，windows下没有经过测试可能会有一些编码问题 :)

**Comment by ly0** [comment]
@zzploveyou 更新了一下 尝试一下?
