### ISSUE TITLE
现在好像不能申请pcs的api了？

### ISSUE THREAD

**Issue by trulyliu** [ly0/baidupcsapi#60]
现在好像不能申请pcs的api了？
相关链接都无效了。
怎么解决？

**Comment by ly0** [comment]
是
这个项目是模拟登陆的。

**Comment by trulyliu** [comment]
能离线下载吗？

**Comment by ly0** [comment]
可以的

https://github.com/ly0/baidupcsapi/blob/master/baidupcsapi/api.py#L1431
