### ISSUE TITLE
PCS初始化提示输入验证码

### ISSUE THREAD

**Issue by MasterColor** [ly0/baidupcsapi#68]
PCS对象初始化阶段要求输入验证码
但是根据提示想要打开验证码文件，提示文件正在被编辑 无法查看
![image](https://user-images.githubusercontent.com/28705375/34252480-c9503b5c-e67e-11e7-811d-cbba63fd0255.png)

验证码能不能做到自动识别输入
或者在什么情况下 登陆需要输入验证码 有没有办法可以避免输入验证码

**Comment by ly0** [comment]
你可以传入验证码处理的函数的, 初始化PCS类的时候传入captcha_callback参数即可。
识别验证码不在这个repo的范围内，需要验证码的机制上，这个真的得问百度。。。

**Comment by MasterColor** [comment]
兄弟 我再向你了解一个问题哈
我看你写的这个python工具，登陆鉴权使用的应该是用户自己的账号对吧，所以会存在可能需要输入验证码的状况；但是你写的很多调用PCS接口的地方，header里面都有一个参数叫app_id 我没理解错的话 这个应该是开发者去百度申请的吧，那为什么不用OAuth授权方式呢，这样让SDK使用者参考百度官网资料自己去生成access_token 这样可以避免验证码哦

**Comment by MasterColor** [comment]
还有一个问题，我看了 你调用的接口 和我在下面的连接找到的接口不太一样，可以透露一下，这些接口你是怎么知道的吗
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list

**Comment by ly0** [comment]
百度pcs早都不能申请了哦。
接口，开chrome debugtool，就知道了。

**Comment by MasterColor** [comment]
我现在 解决了 验证码的问题之后 又阻塞在了邮件验证的地方，提示输入
Input verify code > 畸形玄幻
Verification Code> 
但是一直没有收到验证邮件，我改成SMS验证也不行

**Comment by MasterColor** [comment]
百度这套登陆获取token 的方式 在浏览器登陆之后 再到浏览器里面调用你写的 获取token的接口能拿到有效的token不？
http://passport.baidu.com/v2/api/?getapi&tpl=mn&apiver=v3&class=login&tt=%s&logintype=dialogLogin&callback=0' % int(
                        time.time())
