### ISSUE TITLE
Maybe change the project readme to reflect it requires python 3.0

### ISSUE THREAD

**Issue by yijiem** [ly0/baidupcsapi#82]
I think the project has already dropped its support for python2? For example:

https://github.com/ly0/baidupcsapi/blob/a8db1f7f55a69c62bc7503f00b7a0c201ab9a70d/baidupcsapi/api.py#L15

Shall we change the project readme file to reflect that?

**Comment by ly0** [comment]
You are right, python2 is not supported anymore, and we should mention that in README particularly.

Thanks for your issue, and sorry for the long time reply.
