### ISSUE TITLE
又出现{"error_code":31023,"error_msg":"param error","request_id":5497161907554365330}问题了。。。

### ISSUE THREAD

**Issue by wanderersean** [ly0/baidupcsapi#84]
使用上传文件的功能时出问题了：
```
with open('test.txt', 'rb') as f:
        response = pcs.upload('/', f, 'test.txt')
        print(response.content)
```
返回了
`{"error_code":31023,"error_msg":"param error","request_id":5497161907554365330}`
是我写的不对吗。。。

**Comment by ly0** [comment]
尚不知道这个接口还是否可用,或者需要特殊的姿势

可以试试用传大文件的方式上传?

**Comment by wanderersean** [comment]
@ly0 特殊的姿势。。也是醉了。。刚刚试了一下大文件的上传方式还是可以用的，谢谢作者的回复哈哈。不过还是想向作者请教一下，这些上传下载登录的接口是怎么找出来的呢，能否科普一下具体一点的思路？小白一个，万分感谢作者！！！

**Comment by ly0** [comment]
可以事实 #83 的PR,目前已经合并到master
