### ISSUE TITLE
PIL控制台显示出的图片不清晰

### ISSUE THREAD

**Issue by capric8416** [ly0/baidupcsapi#9]
![vcode](https://cloud.githubusercontent.com/assets/7124338/9679955/b7618566-5325-11e5-82ed-458aef3520a4.png)

建议不直接显示图片，而是给出验证码图片的url，由用户在浏览器打开

**Comment by ly0** [comment]
参考 https://github.com/ly0/baidupcsapi/issues/3

**Comment by capric8416** [comment]
已参考，但不应该把验证码下载下来，而是把URL传出来，这样自定义处理方法会更方便些
def show_captcha(self, url_verify_code):  # old is 'def show_captcha(self, jpg):'

**Comment by ly0** [comment]
考虑到验证码URL可能需要带有cookies访问才能正确获取，所以就把获取验证码的部分封装了起来，如真有需要可以复写`BaseClass._get_captcha`方法，使它返回URL，并且指定自己的captcha_handler来处理这一部分。

**Comment by capric8416** [comment]
已验证，不需要带cookie
一般来讲，大站的图片资源不会限制referer和cookie，这样会干扰搜索引擎
我已经修改fork了个分支做了修改，还加入了磁力链下载支持，稍后放出链接，看可否pull request

**Comment by capric8416** [comment]
求合并pull request
https://github.com/ly0/baidupcsapi/pull/10
去除PIL依赖，不建议使用这种不再维护的库
去除bencode依赖，计算种子hash改用网盘API实现
加入磁力链支持，合并离线下载入口，判断source_url来实现磁力链、种子、其他下载方式的调用

**Comment by ly0** [comment]
在pull request #10 提了几个问题，求解决一下，见 **Line comment**
https://github.com/ly0/baidupcsapi/pull/10/files
